config/routes.rb
Rails.application.routes.draw do
  resources :builders
  get 'pages/about'

  get 'pages/contact'

  root 'builders#index'

end

app/models/builder.rb
class Builder < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/builders_controller.rb
class BuildersController < ApplicationController
  before_action :set_builder, only: [:show, :edit, :update, :destroy]

  # GET /builders
  # GET /builders.json
  def index
    @builders = Builder.all
  end

  # GET /builders/1
  # GET /builders/1.json
  def show
  end

  # GET /builders/new
  def new
    @builder = Builder.new
  end

  # GET /builders/1/edit
  def edit
  end

  # POST /builders
  # POST /builders.json
  def create
    @builder = Builder.new(builder_params)

    respond_to do |format|
      if @builder.save
        format.html { redirect_to @builder, notice: 'Builder was successfully created.' }
        format.json { render :show, status: :created, location: @builder }
      else
        format.html { render :new }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builders/1
  # PATCH/PUT /builders/1.json
  def update
    respond_to do |format|
      if @builder.update(builder_params)
        format.html { redirect_to @builder, notice: 'Builder was successfully updated.' }
        format.json { render :show, status: :ok, location: @builder }
      else
        format.html { render :edit }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builders/1
  # DELETE /builders/1.json
  def destroy
    @builder.destroy
    respond_to do |format|
      format.html { redirect_to builders_url, notice: 'Builder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_builder
      @builder = Builder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def builder_params
      params.require(:builder).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builders_helper.rb
module BuildersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/builders/_form.html.erb
<%= form_for(@builder, :html => {multipart: true}) do |f| %>
  <% if @builder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@builder.errors.count, "error") %> prohibited this builder from being saved:</h2>

      <ul>
      <% @builder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/builders/edit.html.erb
<h1>Editing Builder</h1>

<%= render 'form' %>

<%= link_to 'Show', @builder, class: "btn btn-link" %> |
<%= link_to 'Back', builders_path, class: "btn btn-link" %>

app/views/builders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builders</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builders.each do |builder| %>
      <tr>
        <td><%= builder.name %></td>
        <td><%= builder.address %></td>
        <td><%= builder.phone %></td>
        <td><%= builder.website %></td>
        <td><%= link_to 'Show', builder , class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_builder_path(builder) , class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', builder, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Builder', new_builder_path %>

app/views/builders/new.html.erb
<h1>New Builder</h1>

<%= render 'form' %>

<%= link_to 'Back', builders_path, class: "btn btn-link" %>

app/views/builders/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @builder.image_url %>

<p>
  <strong>Name:</strong>
  <%= @builder.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @builder.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @builder.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @builder.website %>
</p>



<%= link_to 'Edit', edit_builder_path(@builder) , class: "btn btn-link"%> |
<%= link_to 'Back', builders_path , class: "btn btn-link"%>

app/views/layouts/_bootstrap.html.erb
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

app/views/layouts/_footer.html.erb
<p> Copyright Schwikk Analytics </p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">homemakerbox</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>homemakerbox</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

<%= render 'layouts/bootstrap' %>

</head>
<body>

	<%= render 'layouts/navbar' %>
	<div class="container-fluid">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<a href="/pages/about"> About</a>
<a href="/pages/contact"> Contact</a>
<h1>Welcome to HomeBuilder!</h1>
<h2>Review providers of home services and find reliable suppliers</h2>
<p>Still in beta and a sample application in development</p>

app/views/pages/contact.html.erb
<a href="/pages/about"> About</a>
<a href="/pages/contact"> Contact</a>
<h1>We would love to hear from you!</h1>
<p>Contact us at graham@homebuilder.builder</p>